### ISSUE TITLE
Source address X of drive element at address Y does not correspond to any existing element.

### ISSUE THREAD

**Issue by thiell** [phobos-storage/phobos#13]
Using phobos 2.0, I often see the following error message in the logs:
```
<ERROR> Source address '0xXXXX' of drive element at address '0xYYY' does not correspond to any existing element. We will search a free slot address to move.: Cannot assign requested address (99)
```

Example with `phobos drive unload 10130057FB`:

```
Jun 10 17:36:08 elm-ent-dm01 phobosd[10729]: 2024-06-10 17:36:08.779861000 <INFO> umount: medium '058160L9' in device '/dev/sg11' mounted at '/mnt/phobos-sg11'
Jun 10 17:36:08 elm-ent-dm01 systemd[1]: mnt-phobos\x2dsg11.mount: Deactivated successfully.
Jun 10 17:36:21 elm-ent-dm01 ltfs[19125]: 4ab5 LTFS17235I Writing index of 058160 to a (Reason: Unmount, 174 files) 10140057FB.
Jun 10 17:36:29 elm-ent-dm01 ltfs[19125]: 4ab5 LTFS17236I Wrote index of 058160 (Gen = 23, Part = a, Pos = 5, 10140057FB).
Jun 10 17:36:29 elm-ent-dm01 ltfs[19125]: 4ab5 LTFS11034I Volume unmounted successfully.
Jun 10 17:36:29 elm-ent-dm01 ltfs[19125]: 4ab5 LTFS30252I Logical block protection is disabled.
Jun 10 17:36:29 elm-ent-dm01 tlc[3159]: 2024-06-10 17:36:29.904212000 <ERROR> Source address '0x1278' of drive element at address '0x103' does not correspond to any existing element. We will search a free slot address to move.: Cannot assign requested address (99)
```

The umount is successful though, in this case the tape was moved to 0x1269:

```
slot: address=0x1269 source_address=0x103 volume='058160L9' accessible full
slot: address=0x1278 accessible
drive: address=0x103 device_id='10140057FB' accessible
```

Is this something to worry about? Could it be that Phobos is not properly tracking the source of the tape?

**Comment by patlucas** [comment]
Hi Stéphane,

By default, when it comes to unload a drive, Phobos effectively tries to unload the tape into the source adress of the tape. If this slot is no longer available, then Phobos chooses the first available free slot.

Your error message indicates that Phobos considers that your source address is an invalid one whereas it is clearly a valid one. We have to check this error. We come back to you as soon it is fixed.

**Comment by patlucas** [comment]
Hi Stéphane,

The bug is fixed. (The source address was not really taken into account and a bad one was checked.) The bug fix (very short commit of only 4 lines) should be integrated to master at the end of the current sprint scheduled for the end of this week.

**Comment by patlucas** [comment]
The commit fixing this bug is integrated to master : 
https://github.com/phobos-storage/phobos/commit/4757418d00fa8ee60cb0ff1b8de75c4d0e522faf .

Next tagged version is scheduled for the end of the current sprint and will contain this patch.
