### ISSUE TITLE
phobos tape format only uses local drives?

### ISSUE THREAD

**Issue by thiell** [phobos-storage/phobos#8]
With the current master branch, I noticed that `phobos tape format` only uses the drives configured for the local server (where the command is run from). We have 4 data movers, each with 4 drives configured in Phobos, and I have the following configuration:
```
[io_sched_tape]
read_algo = grouped_read
write_algo = fifo
format_algo = fifo

dispatch_algo = fair_share
# Minimum number of LTO9 drives for read, write and formats respectively
fair_share_LTO9_min = 0,0,0
# Maximum number of LTO9 drives for read, write and formats respectively
fair_share_LTO9_max = 16,16,16
```

Without read/write going on, as fair_share_LTO9_max for format is set to 16, it should use all 4 drives per data movers (16 total), however only the tape drives from the local server are considered (`currently_dedicated_to` switches to "F" but not for the other servers). If I launch  `phobos tape format` from another server, then its local drives are used to format and they work.

I think it used to work with 1.95.1 (not 100% sure though). Not critical as format is relatively rare but I wanted to raise the issue.

**Comment by patlucas** [comment]
Hello Stéphane,

Each "phobos tape format" command is effectively a "local" one and uses the local phobosd server.

But more than the format command, the phobos configuration file is also a "local" one. When you write " fair_share_LTO9_max = 16,16,16 " in your configuration file, it is only to allow the local phobosd server to run up to 16 drives. There is no sum or clustering between all phobosd servers. So if your local phobosd has only 4 drives, your can write " fair_share_LTO9_max = 4,4,4" in your configuration file.

**Comment by thiell** [comment]
Hello Patrice,

Thank you for the clarification! It makes sense.
